version: "3.7"

services:
  quirrel:
    image: docker.pkg.github.com/quirrel-dev/quirrel/quirrel
    environment:
      REDIS_URL: redis://redis
    ports:
      - 9181:9181

  redis:
    image: redis
